---
- name: name of playbook
  hosts: all
  connection: docker
  tasks:
    - name: Copy war-file from Jenkins to tomcat
      copy:
        src: /var/jenkins_home/workspace/trial_mustafprojekt_indu2@2/target/spring-boot-webblog.war
        dest: /usr/local/tomcat/webapps
        mode: '0644'