version: '3.8'
networks:
    miniprojekt:
        driver: bridge
        name: miniprojekt
services:
    mysql:
        image: mysql:latest
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        ports:
            - 3306:3306
        expose:
            - 3306
        networks:
            - miniprojekt

    tomcat:
        image: tomcat:latest
        container_name: tomcat
        environment::
            - TOMCAT_USERNAME=admin
            - TOMCAT_PASSWORD=admin
        ports:
            - 8787:8080
        expose:
            - 8787
        networks:
            - miniprojekt
